name: note_design
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  circular_seek_bar: ^1.1.1
  dashed_circular_progress_bar: ^0.0.6
  step_progress_indicator: ^1.0.2
  flutter_slidable: ^3.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SM
      fonts:
        - asset: assets/fonts/ShabnamMedium.ttf

    - family: SB
      fonts:
        - asset: assets/fonts/ShabnamBold.ttf

